app/.prettierrc.json, app/.storybook/i18next.js, app/.storybook/main.js, app/.storybook/preview.js, app/__mocks__/styleMock.js, app/jest.config.js, app/next-i18next.config.js, app/next.config.js, app/src/api/hello.ts, app/src/components/Layout.tsx, app/src/pages/_app.tsx, app/src/pages/index.tsx, app/stories/components/Layout.stories.tsx, app/stories/pages/Index.stories.tsx, app/styles/_uswds-theme-custom-styles.scss, app/styles/_uswds-theme.scss, app/styles/styles.scss, app/tests/components/Layout.test.tsx, app/tests/jest-i18n.ts, app/tests/jest.setup.js, app/tests/pages/index.test.tsx
#24 
This PR removed some non-default settings for prettier and then also made the formatting changes associated with that setting change. The setting change and the format change are in separate commits, in case that makes it easier to review.
All changes should be non-functional, so just visual confirmation that this looks right is probably all that's needed. Rationale for the change is provided in the issue (#24).
Non-functional changes, so little testing was needed, but I still ran storybook and the next.js app to make sure those still work, and they did.
=> Reduce prettier overrides

app/README.md, app/src/components/Layout.tsx, app/src/pages/index.tsx, app/styles/_uswds-theme-custom-styles.scss, app/tests/pages/__snapshots__/index.test.tsx.snap
Resolves #18 
These changes removed many of the custom style elements from the template. There was also a minor update to the readme file to help new users run the test script.
Details in #18; while these changes make the template look slightly less polished, the intention was to allow users of this template to use their own style elements, either from uswds or from their agency, without needing to pull out or overwrite custom style elements from the template.
```
Test Suites: 2 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   2 passed, 2 total
Time:        1.128 s
Ran all test suites.
```
Before:
After:
=> Remove non-uswds style elements from template

app/README.md
resolves #23
This changeset is only updating the documentation of the `package.json` file in the Readme.
I added documentation for all of the dependencies in scripts that are in `package.json`. I'm not super experienced with frontend repos, so some of my terminology and descriptions may be imprecise, I'm very open to suggestions and feedback on that.
I previewed the Markdown and it looks as expected.
=> Readme updates to sync with `package.json`

app/next-i18next.config.js
- Enable the `reloadOnPrerender` option of `next-i18next` when running the app locally. This will allow developers to edit `public/locales/` files and reload their browser to see the changes. Prior to this, you would need to restart the server and then reload the page, which is a fairly big impact to productivity depending on the dev's workflow.
=> Support locale reloading during local dev

app/README.md, app/src/components/Layout.tsx, app/src/pages/index.tsx, docs/internationalization.md
#22 
- Split out Internationalization documentation into its own file and added additional usage documentation
- Import `useTranslation` from `react-i18next` instead of `next-i18next`. Primary reasoning is because `next-i18next` is just returning the methods from `react-i18next`, and I think it'll be clearer to engineers where they should search for relevant documentation if the import is from the library that's providing the methods.
=> Expand usage documation for internationalization

app/.storybook/main.ts
Closes #21 
- Enable Storybook's [lazy compilation](https://storybook.js.org/docs/react/builders/webpack#lazy-compilation) and [filesystem caching](https://storybook.js.org/docs/react/builders/webpack#filesystem-caching). These two features improve the startup time (mostly noticeable for larger projects).
- Convert the Storybook config file to TypeScript to receive type checking. This can help catch invalid or deprecated config options.
=> Optimize Storybook for quick startup; Convert Storybook config to TS.

app/.storybook/i18next.js, app/package.json, app/tests/jest-i18n.ts
- Remove the `resources` option from Storybook's i18next initialization. We're utilizing the `i18next-http-backend` package for loading locales in Storybook via HTTP requests, so manually setting them doesn't appear to be required for it to render the strings.
- Update Jest's i18next initialization to dynamically set `resources` based on the file structure. This removes the need for updating the Jest setup file every time a new language file is created.
- Fix the `test-update` script
=> Dynamically set i18n resources for Storybook and tests

app/package-lock.json, app/package.json
Closes #65
Next.js 13 introduced [pretty significant new functionality](https://nextjs.org/blog/next-13), but it's backwards compatible with the existing approach implemented in this repo, so should be safe to upgrade. Projects can adopt its new functionality as they want. We have a separate ticket for adopting the new functionality in this repo: #66
=> Upgrade to Next.js 13

app/next-i18next.config.js
- Disable i18next's escaping functionality in order to fix strings being double-escaped.
With a string like: 
```
"status_upcoming": "Certification opens on {{date, datetime}}",
```
Before:
After:
=> Fix double-escaping in internationlized strings

renovate.json
- We noticed some of the renovate grouping wasn't working well, so wanted to try tweaking our config a little bit. 
- The main changes here are to rely more on presets - a bit whackamole of an attempt but I read a lot of renovate.json files and further into the renovate preset documentation to put this together.
=> Improve renovate grouping

.github/workflows/template-only-cd.yml, README.md, template-only-bin/download-and-install-template.sh, template-only-bin/install-template.sh, template-only-bin/update-template.sh
Resolves #94 
* Add template-only-cd which deploys the application template to the platform-test-nextjs test project repo after merges
* Rename install-template.sh to download-and-install-template.sh and split out the cp commands into an install-template.sh script
* Add an update-template.sh script that resets files the project will have modified from the template
Context from ticket:
In order to continuously integrate template-infra and template-application-nextjs, we should deploy changes to template-application-nextjs to the platform-test-nextjs repo, which is the repo we're using to test the integration of the two templates.
We are already doing this with template-infra in https://github.com/navapbc/template-infra/issues/196, this is the corresponding ticket for …
=> Deploy template to platform-test-nextjs on merges

app/.storybook/main.js
https://github.com/navapbc/template-application-nextjs/issues/97
> What was added, updated, or removed in this PR.
- Update regex for storybook string replacement to support deploying to a subdirectory
> Testing instructions, background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers. Explain how the changes were verified.
I deployed https://github.com/navapbc/template-application-nextjs/pull/89 to WIC MT Demo Project in order to get our storybook deployed using github pages. I found an issue where the images weren't displaying properly and made a PR for it: https://github.com/navapbc/wic-mt-demo-project-eligibility-screener/pull/168 This PR is a port of that one.
See also Slack discussion: …
=> Update storybook config to display USWDS images when deploying to a subdir

.grype.yml, app/Dockerfile, app/Makefile
N/A
* Configure grype to ignore vulnerabilities in dev dependencies
* Configure grype to ignore false positives (vulnerabilities in packages that aren't in the app)
* Use non-root user in Docker container (addresses issue discovered by scanners)
* Use JSON syntax for Docker start CMD (addresses issue discovered by dockle scanner)
This PR https://github.com/navapbc/template-infra/pull/203 introduced a new CI check that scans containers for vulnerabilities. The template-application-nextjs Docker container currently fails some of those scans:
- hadolint scan warning to use JSON notation for docker CMD https://github.com/navapbc/platform-test-nextjs/actions/runs/4318667731/jobs/7537233036
- anchore scan for package vulnerabilities https://github.com/navapbc/platform-test-nextjs/actions/runs/43 …
=> Fix container vulnerabilities

template-only-bin/install-template.sh
n/a
see title
PR https://github.com/navapbc/template-application-nextjs/pull/124 added scanner configs to the template but we didn't add it to the template installation script, so [one of the vulnerability scans is still failing](https://github.com/navapbc/platform-test-nextjs/actions/runs/4345788954)
Didn't do testing but I think this is a simple and low risk enough change
=> Copy scanner configs on install

.grype.yml
{LINK TO TICKET}
see title
Sorry my mistake, this actually is a real dev dependency
```
➜  app git:(lorenyu/recategorizetrimnewlines) npm ls trim-newlines
app@0.1.0 /Users/lorenyu/Projects/platform/template-application-nextjs/app
└─┬ @storybook/react@6.5.12
└─┬ @storybook/core@6.5.12
└─┬ @storybook/core-server@6.5.12
└─┬ x-default-browser@0.4.0
└─┬ default-browser-id@1.0.4
└─┬ meow@3.7.0
└── trim-newlines@1.0.0
```
none, no functional change
=> Recategorize trim-newlines as dev tool not false positive

app/.storybook/main.js, app/next.config.js, app/package.json, app/scripts/sassOptions.js, app/styles/_uswds-theme.scss
- Expose a new `add-base-path` function to our Sass files, to support hosting the site at a subdirectory.
- Preconfigure Next.js so that the relative paths in our Sass files output the correct path when Next.js's `basePath` property is configured.
Setting `basePath` to `/test` results in the site's index becoming `localhost:3000/test`. Therefore any relative link should be relative to `/test` (e.g. `/test/img/foo.png`).
Temporarily set the `basePath` to `/test` and confirmed the fonts still load:
=> Make it easier to configure Next.js’s basePath config without breaking static assets

app/.storybook/main.js
Resolves #155 
- https://storybook.js.org/docs/react/api/main-config-manager-head
- https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag
=> Block search engines from indexing Storybook

app/Dockerfile, app/Makefile
n/a
* Fix semver vulnerability in base image
* Target release stage explicitly in make release-build
Tackling the stubborn last vulnerability in the anchor scan
Made the changes in platform-test-nextjs repo in this PR: https://github.com/navapbc/platform-test-nextjs/pull/79
- You can see that the scans all pass!
- Also triggered e2e tests to show that the service still works
=> Fix semver vulnerability in base image

app/Dockerfile
- Update `Dockerfile` release stage to remove `yarn`, for similar reasons as #175 
- Even though Yarn isn't included in the official Node installation, [the Docker image does install it](https://github.com/nodejs/docker-node/blob/31bc0387d4a2eea9e9fee4d5b1f8dca0e0596dca/18/bullseye-slim/Dockerfile#L56-L88).
- Issue from 2018 asking for it to not be in the official image, but seems unlikely to be going away: https://github.com/nodejs/docker-node/issues/777
=> Remove yarn from Docker release stage

app/Dockerfile
n/a
- Add wget to release build
- Also port over the `apt-get upgrade` and removal of apt cache lists, since those seemed like good ideas too
- from https://github.com/navapbc/template-application-flask/blob/main/app/Dockerfile#L21
- wget is required for health checks
=> Add wget to release build

app/next-i18next.config.js
- Define which i18n namespace should be loaded if not defined at the page/component level. This fixes an issue I observed when Storybook is deployed to Chromatic, where Chromatic would be very slow to load because it attempts to load `translation.json` which is the default `ns` when it's not defined in the config.
https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
It would make several attempts to load the translation file, and would only render the story after six failed requests:
No errors, and the Story loads right away
=> Set default i18n namespace to fix slow Storybook+Chromatic behavior

app/Makefile
All of the other scripts use `docker compose` but this one was using `docker-compose` which I think is an old way of running this.
=> Use `docker compose` in `make stop`

app/.eslintrc.js, app/package-lock.json, app/package.json
Resolves #193 
See context in #193
=> Remove eslint-config-nava in favor of eslint:recommended and Next.js built-in lint config

.github/pull_request_template.md
- Update the PR template to use HTML comments, so that they aren't rendered in the published PR request.
- Replace LICECap with Kap as the recommended GIF recorder. Kap is newer and more maintained. I don't think LICECap works on M1 Macbooks for instance.
=> Use HTML comments in PR template; Update suggested GIF record.

docs/decisions/app/0007-i18n-type-safety.md
Relates to #194 
An implementation can be seen at https://github.com/navapbc/template-application-nextjs/pull/199
=> Add ADR for enabling i18n type checking

app/.eslintrc.js, docs/internationalization.md
- Add lint rule to require imports from `next-i18next` rather than `react-i18next`, otherwise the site will report hydration errors due to server-side renders not outputting the translated text
- Update docs to clarify how i18n namespaces work
=> Add lint rule to require imports from next-i18next rather than react-i18next

app/.gitignore, app/package-lock.json, app/package.json
- Fix issue where some projects weren't getting the Jest types, which makes sense, since we aren't installing the package as a direct dependency: https://jestjs.io/docs/getting-started#type-definitions
- Ignore generated files when running tests
=> Add missing Jest types package

app/package.json
- Fix common issue where a test passes locally, but fails in the CI or on other engineers' machines, because of a difference in timezone
=> Set consistent timezone for tests

app/package.json
This reverts commit 5db0ceaac6f2625e6392d87b020ee55f23bb5f3b.
Projects can mock timezone within the relevant tests. Mocking globally could hide bugs. See convo on #209.
=> Revert "Set consistent timezone for tests (#209)"

app/.storybook/preview.js, app/src/pages/index.tsx, app/src/styles/_uswds-theme.scss, app/stories/typography.stories.tsx
- Enable USWDS settings to apply global typography styles (size, color, spacing)
- Add a new Typography storybook section for previewing global type styles and provide examples of using typography utility classes
The intent (I think) of these USWDS settings being disabled by default is to not interfere with a site's existing styles. The downside is teams must apply a good bit of the utility classes in order to style headings and paragraphs the way they want. 
The intent of the template is to help teams quickly create new applications, so the risk of interfering with an existing site's styles isn't as applicable, and it would be more beneficial to have global styles from the start, to reduce the need for utility classes.
=> Enable global USWDS typography styles

app/next.config.js
- Configures Next.js to transpile the React USWDS and React I18next packages to address an issue where its syntax was breaking the experience for Safari versions prior to 14, and Edge versions prior to 79.
I've filed a ticket on the React USWDS repo about one of the issues here: https://github.com/trussworks/react-uswds/issues/2605
The two JS exceptions we were seeing are:
1. [`Unexpected token '='`](https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet)
2. [`Expected identifier, string or number`](https://confluence.atlassian.com/insightapps/known-issue-with-older-versions-of-microsoft-edge-1085191263.html)
Before
After
=> Fix broken experience for older Safari and Edge

app/README.md, app/jest.config.js, app/src/components/Layout.tsx, app/src/pages/health.tsx, app/src/pages/index.tsx, app/tests/jest-i18n.ts, docs/internationalization.md
Various fixes I originally had made in the App Router migration branch, which is now on pause, so pulling over into `main`
- Fix sticky footer
- Expand testing docs and fix file structure 
- Remove unused jest setup file
- Fix i18n on health page
- Move `getServerSideProps` to top of each file
=> Fix sticky footer and health page i18n + update documentation

app/tsconfig.json
- Only include the directories we care about, so that we don't accidentally include build folders with tons of folders, which can slow down compilation and type checking.
I made this change on my other project and it cut type checking time in half:
Type checks took around 40 seconds:
Type checks now take around half of what it did before:
=> Optimize TypeScript config

app/.storybook/main.js, app/README.md, app/src/app/[locale]/page.stories.tsx, app/src/app/[locale]/page.test.tsx, app/src/components/Header.test.tsx, app/src/components/Layout.stories.tsx, app/src/components/Layout.test.tsx
Resolves #271
- move existing unit test files into same folder with the file they reference
- move existing Storybook story files into same folder with the file they reference
- update Storybook config to load files from anywhere under `src` folder
=> Colocate Test and Story Files with Code

.github/workflows/ci-app.yml
- Don't annotate lines of code that lack test coverage. It's too noisy, making a PR's file changes difficult to parse when reviewing a PR.
=> Disable noisy test coverage annotations

app/README.md, app/package-lock.json, app/package.json, app/src/adapters/feature-flags/EvidentlyAdapter.ts, docs/app/security.md
=> Mark Evidently class as server-only

app/Dockerfile
Resolves #305
- Set `HOSTNAME` for the Docker container. This fixes an issue where the healthcheck fails after upgrading to Next.js 13.4.13+
This was copied from the [Next.js Docker example](https://github.com/vercel/next.js/blob/3438b39fcfd64bec35cbc397d687744a7f3f66df/examples/with-docker/Dockerfile#L67C1-L67C38). I tried a [few](https://github.com/navapbc/platform-test-nextjs/commit/f1d0cb06ad95fe6ab8a2f2a27746b1c6a179b1b1) other [formats](https://github.com/navapbc/platform-test-nextjs/commit/fd933f911dbfd4e93c443d3fc0f31d76bb127aea), but none of those worked.
Tested on the [Platform test app](https://github.com/navapbc/platform-test-nextjs)
=> Fix AWS health check

.github/workflows/template-only-docs.yml, .github/workflows/template-only-markdownlint-config.json, docs/app/internationalization.md, docs/decisions/app/0003-design-system.md, docs/decisions/app/0005-server-rendering.md, docs/decisions/template/0001-use-renovate-for-dependency-updates.md, template-only-bin/lint-markdown.sh, template-only-docs/set-up-dependency-management.md
Resolves #264
The infra template includes a workflow that is installed along with the template. This just adds a template-only workflow so the CI catches bad links as they happen.
https://github.com/navapbc/template-application-nextjs/actions/runs/8884261284/job/24392951892?pr=331
=> Add Markdown link checker + fix links

template-only-bin/install-template.sh, template-only-bin/update-template.sh
This should fix an issue with the install/update script, since the infra template also installs/updates this file.
Tested the install script locally:
=> Exclude template.md from install/update

app/package.json
Resolves #280 
- add min node/npm version
- can't `npm install` with an older version of node
=> [Issue #280]: add node/npm min versions to package.json

template/{{app_name}}/.storybook/main.js
Resolves #387 
Updated the `.storybook/main.js` in the top-level app directory.
The error occurs when running `npm run storybook` from the terminal to build a dev Storybook environment locally. I added the code below at the top of the file to explicitly set a __dirname value.
```
import path, { dirname } from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
```
According to [Node.js documentation](https://nodejs.org/api/esm.html#differences-between-es-modules-and-commonjs), `__dirname` is unavailable in ES modules. They recommend [import.meta.dirname](https://nodejs.org/api/esm.html#importmetadirname) instead to replicate this behavior. 
I was able to find use cases for the recommended solution in this …
=> [Issue #387]: Resolved Storybook build error

template/{{app_name}}/.storybook/main.mjs, template/{{app_name}}/next-env.d.ts
Resolves #387 
- Updated .storybook/main.js => .storybook/main.mjs based on ECMAScript Modules instead of CommonJS
- **.storybook/main.mjs:**
```    
path.resolve(import.meta.dirname, "../next.config.js")
```
Originally made an update to Storybook in #388 meant to address #387. Making these changes caused issues in [platform-test-nextjs](https://github.com/navapbc/platform-test-nextjs/actions/runs/13999633004/job/39317883628). 
The steps taken to resolve are in this [PR](https://github.com/navapbc/platform-test-nextjs/pull/98).
Making this change in platform-test-nextjs resulted in a successful app build (save for a vulnerability scan). This change also follows [Node.js documentation](https://nodejs.org/docs/latest/api/esm.html#no-__filename-or-__dirname) on what they recommend to use in …
=> [#387] Update Storybook nextConfigPath to support node modules

template/docs/decisions/{{app_name}}/0006-use-nextjs.md
Lint is failing for the project because the link to middleware documentation for NextJS has changed with the latest version. Updating the link to reference the current documentation on the NextJS website.
=> Updating broken link to middleware docs for NextJS
